export const START_ROUTE = '/'
export const AUTH_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const PROFILE_ROUTE = '/profile'
export const SEARCH_ROUTE = '/search'
export const USERPAGE_ROUTE = '/user'